; Inno Setup Script for Vision Attendance System
; Generated by Antigravity

[Setup]
AppId={{D3F4B5C6-7E8F-4A9B-B0D1-E2F3G4H5I6J7}
AppName=Vision Attendance System
AppVersion=1.0.0
AppPublisher=Prosper Infotech
DefaultDirName={autopf}\VisionAttendance
DefaultGroupName=Vision Attendance System
AllowNoIcons=yes
OutputDir=Output
OutputBaseFilename=VisionAttendance_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startup"; Description: "Run on Windows Startup"; GroupDescription: "Additional options:"; Flags: unchecked

[Files]
Source: "dist\VisionAttendance\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Vision Attendance System"; Filename: "{app}\VisionAttendance.exe"
Name: "{commondesktop}\Vision Attendance System"; Filename: "{app}\VisionAttendance.exe"; Tasks: desktopicon

[Registry]
; Add to startup if task is selected
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "VisionAttendance"; ValueData: """{app}\VisionAttendance.exe"""; Tasks: startup

[Run]
Filename: "{app}\VisionAttendance.exe"; Description: "{cm:LaunchProgram,Vision Attendance System}"; Flags: nowait postinstall skipifsilent
